[package]
name = "examples"
authors = ["Rafael Lemos <contact@flemosr.com"]
edition = "2021"
publish = false
version = "0.1.0"

[[example]]
name = "authorization-server-basic"
path = "src/ext_authz/authorization_server_basic.rs"

[[example]]
name = "authorization-server-full"
path = "src/ext_authz/authorization_server_full.rs"

[[example]]
name = "authorization-server-pb-only"
path = "src/ext_authz/authorization_server_pb_only.rs"

[dependencies]
envoy-types = { path = "../envoy-types" }
tokio = { version = "1.29.1", features = ["rt-multi-thread", "macros"] }
tonic = "0.10.2"
